### ISSUE TITLE
Update to Angular2 RC1

### ISSUE THREAD

**Issue by amaury1093** [tixdo/ng2-popover#1]
Hey tixdo,

Do you plan to update your code to support angular2-rc1?

More info here:
https://github.com/angular/angular/blob/master/CHANGELOG.md

Thanks!

**Comment by abhinavsohani** [comment]
Hi amaurymartiny,
We are migrating a big project right now form beta to RC. We do have plans to support RC but not sure about timeline.

Thanks

**Comment by paruldixit** [comment]
Updated to Angular 2.0.0.
